#!/bin/bash

set -eou pipefail

CURRENT_DIR=$(dirname "${BASH_SOURCE[0]}")

cd "$CURRENT_DIR"

AWS_REGION="${AWS_REGION:-us-east-1}"
TF_STATE_BUCKET="test-static-null2"
TF_LOCK_TABLE="service-provisioning-terraform-state-lock"
# You need to export the GITHUB_TOKEN as an env var in the agent
#GITHUB_TOKEN=""

APPLICATION_SLUG=$(echo "$CONTEXT" | jq -r .application.slug)
SCOPE_SLUG=$(echo "$CONTEXT" | jq -r .scope.slug)
SCOPE_ID=$(echo "$CONTEXT" | jq -r .scope.id)
REPOSITORY_URL=$(echo "$CONTEXT" | jq -r .application.repository_url)
APPLICATION_VERSION="$(echo "$CONTEXT" | jq -r .release.semver)"
ENV_VARS_JSON=$(echo "$CONTEXT" | jq '.parameters.results | map({(.variable): .values[0].value}) | add')
RESOURCE_TAGS_JSON=$(echo "$CONTEXT" | jq \
     '{
     nullplatform: "true",
     account: .account.slug,
     account_id: .account.id,
     namespace: .namespace.slug,
     namespace_id: .namespace.id,
     application: .application.slug,
     application_id: .application.id,
     scope: .scope.slug,
     scope_id: .scope.id,
     deployment_id: .deployment.id
     }')

 HOSTED_PUBLIC_ZONE_ID=$(echo "$CONTEXT" | jq -r '.providers["cloud-providers"].networking.hosted_public_zone_id')

DOMAIN=$(aws route53 get-hosted-zone --id "$HOSTED_PUBLIC_ZONE_ID" --query 'HostedZone.Name' --output text | sed 's/\.$//')
SUBDOMAIN="$APPLICATION_SLUG-$SCOPE_SLUG"

np scope patch --id "$SCOPE_ID" --body "{\"domain\":\"$SUBDOMAIN.$DOMAIN\"}"

#echo $APPLICATION_SLUG
#echo $SCOPE_SLUG
#echo $SCOPE_ID
#echo $REPOSITORY_URL
#echo $APPLICATION_VERSION
#echo $ENV_VARS_JSON
#echo $RESOURCE_TAGS_JSON
#echo $DOMAIN
#echo $SUBDOMAIN

tofu init \
  -backend-config="bucket=${TF_STATE_BUCKET}" \
  -backend-config="key=amplify/$APPLICATION_SLUG/$SCOPE_SLUG-$SCOPE_ID" \
  -backend-config="region=${AWS_REGION}" \
  -backend-config="dynamodb_table=${TF_LOCK_TABLE}"

tofu $ACTION -auto-approve \
  -var="aws_region=${AWS_REGION}" \
  -var="github_token=${GITHUB_TOKEN}" \
  -var="application_name=${APPLICATION_SLUG}" \
  -var="repository_url=${REPOSITORY_URL}" \
  -var="application_version=${APPLICATION_VERSION}" \
  -var="env_vars_json=${ENV_VARS_JSON}" \
  -var="resource_tags_json=${RESOURCE_TAGS_JSON}" \
  -var="domain=${DOMAIN}" \
  -var="subdomain=${SUBDOMAIN}"