#!/bin/bash

WORKFLOW_PATH="$SERVICE_PATH/log/workflows/log.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/log/workflows/log.yaml"

CMD="np service workflow exec --no-output --workflow $WORKFLOW_PATH"

if [[ -f "$OVERRIDES_WORKFLOW_PATH" ]]; then
  CMD="$CMD --overrides $OVERRIDES_WORKFLOW_PATH"
fi

eval "$CMD"