#!/bin/bash

echo "Getting hosted zones"
HOSTED_PUBLIC_ZONE_ID=$(echo "$CONTEXT" | jq -r '.providers["cloud-providers"].networking.hosted_public_zone_id // .providers["cloud-providers"].networking.hosted_public_zone_name')
HOSTED_PRIVATE_ZONE_ID=$(echo "$CONTEXT" | jq -r '.providers["cloud-providers"].networking.hosted_zone_id // .providers["cloud-providers"].networking.hosted_public_zone_name')

echo "Public Hosted Zone ID: $HOSTED_PUBLIC_ZONE_ID"
echo "Private Hosted Zone ID: $HOSTED_PRIVATE_ZONE_ID"

# Check if both hosted zones are empty or null
if [[ -z "$HOSTED_PUBLIC_ZONE_ID" || "$HOSTED_PUBLIC_ZONE_ID" == "null" ]] && [[ -z "$HOSTED_PRIVATE_ZONE_ID" || "$HOSTED_PRIVATE_ZONE_ID" == "null" ]]; then
    echo "Unable to find any hosted zones (neither public nor private)" >&2
    exit 0
fi

export HOSTED_PUBLIC_ZONE_ID
export HOSTED_PRIVATE_ZONE_ID

mkdir -p "$SERVICE_PATH/tmp/"
mkdir -p "$SERVICE_PATH/output/"
