#!/bin/bash

echo "Getting hosted zones"
HOSTED_ZONES=$(np nrn read --nrn "organization=$ORGANIZATION_ID:account=$ACCOUNT_ID:namespace=$NAMESPACE_ID:application=$APPLICATION_ID:scope=$SCOPE_ID" --ids 'aws.hostedZoneId,aws.hostedPublicZoneId' --format json)
HOSTED_PUBLIC_ZONE_ID=$(echo "$HOSTED_ZONES" | jq -r '.namespaces.aws.hostedPublicZoneId')
# shellcheck disable=SC2086
HOSTED_PRIVATE_ZONE_ID=$(echo $HOSTED_ZONES | jq -r '.namespaces.aws.hostedZoneId')

echo "Public Hosted Zone ID: $HOSTED_PUBLIC_ZONE_ID"
echo "Private Hosted Zone ID: $HOSTED_PRIVATE_ZONE_ID"

export HOSTED_PUBLIC_ZONE_ID
export HOSTED_PRIVATE_ZONE_ID

mkdir -p $SERVICE_PATH/tmp/
mkdir -p $SERVICE_PATH/output/
