#!/bin/bash
CI_ROLE_ID=1855672260
# TODO(federico.maleh) missing support for mono repo
# TODO(federico.maleh) missing support for extra secrets
# TODO(federico.maleh) missing support for extra roles in api key
  
API_KEY_NAME="ci-$NAMESPACE_SLUG-$NAMESPACE_ID-$APPLICATION_SLUG-$APPLICATION_ID"

echo "Creating api key for ci: $API_KEY_NAME"

API_KEY_BODY=$(jq -nc \
  --arg name "$API_KEY_NAME" \
  --arg nrn "$NRN" \
  --argjson role_id "$CI_ROLE_ID" \
  '{name: $name, grants: [{nrn: $nrn, role_id: $role_id}], tags: [{key: "ci", value: true}], internal: true}')

API_KEY_RESPONSE=$(np api-key create --format json --body "$API_KEY_BODY")

API_KEY=$(echo "$API_KEY_RESPONSE" | jq -r .api_key)
API_KEY_ID=$(echo "$API_KEY_RESPONSE" | jq -r .id)

if [[ -n "$API_KEY_ID" ]]; then
  echo "Created ci api key: $API_KEY_ID"
else
  echo "Error creating ci api key"
  echo "$API_API_KEY_RESPONSE" | jq

  exit 1
fi

CODE_REPOSITORY_SECRETS="{\"NP_API_KEY\": \"$API_KEY\"}"

export CODE_REPOSITORY_SECRETS