#!/bin/bash
CI_ROLE_ID=1855672260
# TODO(federico.maleh) missing support for mono repo
# TODO(federico.maleh) missing support for extra secrets
# TODO(federico.maleh) missing support for extra roles in api key
# TODO(federico.maleh) missing add collaborators

API_KEY_NAME="ci-$NAMESPACE_SLUG-$NAMESPACE_ID-$APPLICATION_SLUG-$APPLICATION_ID"

echo "Creating api key for ci: $API_KEY_NAME"

API_KEY_BODY=$(jq -nc \
  --arg name "$API_KEY_NAME" \
  --arg nrn "$NRN" \
  --argjson role_id "$CI_ROLE_ID" \
  '{name: $name, grants: [{nrn: $nrn, role_id: $role_id}], tags: [{key: "ci", value: true}], internal: true}')

API_KEY_RESPONSE=$(np api-key create --format json --body "$API_KEY_BODY")

API_KEY=$(echo "$API_KEY_RESPONSE" | jq -r .api_key)

echo "Created api key for ci"

CODE_REPOSITORY_SECRETS="{\"NP_API_KEY\": \"$API_KEY\"}"

export CODE_REPOSITORY_SECRETS