#!/bin/bash
CI_ROLE_ID=1855672260
# TODO(federico.maleh) missing support for mono repo
# TODO(federico.maleh) missing support for extra secrets
# TODO(federico.maleh) missing support for extra roles in api key
# TODO(federico.maleh) missing add collaborators
# TODO(federico.maleh) missing support for no template use case

API_KEY_NAME="ci-$NAMESPACE_SLUG-$NAMESPACE_ID-$APPLICATION_SLUG-$APPLICATION_ID"

echo "Creating api key for ci: $API_KEY_NAME"

API_KEY_RESPONSE=$(np api-key create --format json --body "{
  \"name\": \"$API_KEY_NAME\",
  \"grants\": [
    {\"nrn\": \"$NRN\", \"role_id\": $CI_ROLE_ID}
  ],
  \"tags\": [{ \"key\": \"ci\", \"value\": true }],
  \"internal\": true
}")


API_KEY=$(echo "$API_KEY_RESPONSE" | jq -r .api_key)
echo "Created api key for ci"

CODE_REPOSITORY_SECRETS="{\"NP_API_KEY\": \"$API_KEY\"}"

export CODE_REPOSITORY_SECRETS