steps:
  - name: apply
    type: script
    file: "$SERVICE_PATH/apply_templates"
    post:
      name: deployment_checks
      type: workflow
      steps:
        - name: notify_active_domains
          type: script
          file: "$SERVICE_PATH/deployment/notify_active_domains"
        - name: wait deployment active
          type: script
          file: "$SERVICE_PATH/deployment/wait_deployment_active"
          configuration:
            TIMEOUT: DEPLOYMENT_MAX_WAIT_IN_SECONDS
