steps:
  - name: build_context
    type: script
    file: "$SERVICE_PATH/deployment/build_context"
    output:
      - name: CONTEXT
        type: environment
      - name: SCOPE_VISIBILITY
        type: environment
      - name: SCOPE_DOMAIN
        type: environment
      - name: OUTPUT_DIR
        type: environment
      - name: DEPLOYMENT_ID
        type: environment
      - name: BLUE_DEPLOYMENT_ID
        type: environment