provider_categories:
  - container-orchestration
  - cloud-providers
configuration:
  K8S_NAMESPACE: nullplatform
  DOMAIN: nullapps.io
  USE_ACCOUNT_SLUG: false
  DNS_TYPE: route53
  DEPLOYMENT_MAX_WAIT_IN_SECONDS: 600
  DEPLOYMENT_TEMPLATE: "$SERVICE_PATH/deployment/templates/deployment.yaml.tpl"
  SECRET_TEMPLATE: "$SERVICE_PATH/deployment/templates/secret.yaml.tpl"
  SCALING_TEMPLATE: "$SERVICE_PATH/deployment/templates/scaling.yaml.tpl"
  SERVICE_TEMPLATE: "$SERVICE_PATH/deployment/templates/service.yaml.tpl"
  BASE_INGRESS_PATH: "$SERVICE_PATH/scope/templates/base-ingress.yaml.tpl"
  INITIAL_INGRESS_PATH: "$SERVICE_PATH/deployment/templates/initial-ingress.yaml.tpl"
  BLUE_GREEN_INGRESS_PATH: "$SERVICE_PATH/deployment/templates/blue-green-ingress.yaml.tpl"
  SERVICE_ACCOUNT_TEMPLATE: "$SERVICE_PATH/scope/templates/service-account.yaml.tpl"
#  TRAFFIC_CONTAINER_IMAGE: "public.ecr.aws/nullplatform/k8s-traffic-manager:latest"
  IMAGE_PULL_SECRETS:
    ENABLED: true
    SECRETS:
      - ecr-secret
  # VAULT_ADDR: "http://localhost:8200"
  # VAULT_TOKEN: "myroot"
  IAM:
    ENABLED: false
#    PREFIX: nullplatform-scopes
#    ROLE:
#      POLICIES:
#        - TYPE: arn
#          VALUE: arn:aws:iam::aws:policy/AmazonS3FullAccess
#        - TYPE: arn
#          VALUE: arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
#        - TYPE: inline
#          VALUE: |
#            {
#              "Version": "2012-10-17",
#              "Statement": [
#                {
#                  "Effect": "Allow",
#                  "Action": [
#                    "sqs:GetQueueAttributes"
#                  ],
#                  "Resource": [
#                    "arn:aws:sqs:*:*:myapp-*"
#                  ]
#                }
#              ]
#            }
#      BOUNDARY_ARN: arn:aws:iam::aws:policy/AmazonS3FullAccess
  MANIFEST_BACKUP:
    ENABLED: false
#    TYPE: s3
#    BUCKET: bucket-name
#    PREFIX: path-prefix
#  DEPLOY_STRATEGY: rolling
#  K8S_MODIFIERS:
#    global:
#      annotations:
#        priority: P3
#      labels:
#        country: argentina
#    service:
#      annotations:
#        some-alb-annotation: value
#      labels:
#        cost-center: payments
#    ingress:
#      annotations:
#        some-ingress-annotation: value
#      labels:
#        cost-center: payments
#    deployment:
#      annotations:
#        datadog-annotation: value
#      labels:
#        cost-center: payments
#      tolerations:
#        - key: "my-taint"
#          operator: "Equal"
#          value: "my-value"
#          effect: "NoSchedule"
#        - key: "my-taint2"
#          operator: "Equal"
#          value: "my-value2"
#          effect: "NoSchedule"
#    secret:
#      labels:
#        cost-center: payments

