#!/bin/bash


print_info "📍 Pod IP: ${pod_ip:-N/A}"

PORTS_INFO=$(kubectl get pod "$pod_name" -n "$K8S_NAMESPACE" -o json | jq -c '[
  .spec.containers[] | {
    containerName: .name,
    ports: (.ports // [] | map({
      containerPort: .containerPort,
      protocol: .protocol,
      name: (.name // "unnamed")
    }))
  }
]')

pod_network_data=$(jq -nc \
    --arg ip "$pod_ip" \
    --arg ports "$PORTS_INFO" \
    '{podIP: $ip, containerPorts: $ports}')

update_check_result --status "success" \
                    --evidence "$pod_network_data" \
                    --output-file "$SCRIPT_OUTPUT_FILE"
