include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: delete deployment
    type: script
    file: "$SERVICE_PATH/apply_templates"
    configuration:
      ACTION: delete
      DRY_RUN: false
    post:
      name: delete_cluster_objects
      type: script
      file: "$SERVICE_PATH/deployment/delete_cluster_objects"
      configuration:
        DEPLOYMENT: green