include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: build context
    type: script
    file: "$SERVICE_PATH/deployment/build_context"
    output:
      - name: CONTEXT
        type: environment
      - name: SCOPE_VISIBILITY
        type: environment
      - name: SCOPE_DOMAIN
        type: environment
      - name: OUTPUT_DIR
        type: environment
      - name: DEPLOYMENT_ID
        type: environment
      - name: BLUE_DEPLOYMENT_ID
        type: environment
  - name: delete ingress finalizer
    type: script
    file: "$SERVICE_PATH/deployment/delete_ingress_finalizer"
  - name: route traffic
    type: script
    file: "$SERVICE_PATH/scope/networking/gateway/build_gateway"
    configuration:
      TEMPLATE: "$INITIAL_INGRESS_PATH"
    output:
      - name: INGRESS_FILE
        type: file
        file: "$OUTPUT_DIR/ingress-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
  - name: build deployment
    type: script
    file: "$SERVICE_PATH/deployment/build_deployment"
    output:
      - name: DEPLOYMENT_PATH
        type: file
        file: "$OUTPUT_DIR/deployment-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
      - name: SECRET_PATH
        type: file
        file: "$OUTPUT_DIR/secret-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
      - name: SCALING_PATH
        type: file
        file: "$OUTPUT_DIR/scaling-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
      - name: SERVICE_TEMPLATE_PATH
        type: file
        file: "$OUTPUT_DIR/service-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
  - name: delete deployment
    type: script
    file: "$SERVICE_PATH/apply_templates"
    configuration:
      ACTION: delete
      DRY_RUN: false