include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: load logging
    type: script
    file: "$SERVICE_PATH/logging"
    output:
      - name: log
        type: function
        parameters:
          level: string
          message: string
  - name: kill instances
    type: script
    file: "$SERVICE_PATH/deployment/kill_instances"