#!/bin/bash

echo "$CODE_REPOSITORY_SECRETS" \
| jq -r 'to_entries[] | [.key, (.value|tostring)] | @tsv' \
| while IFS=$'\t' read -r key value; do
  echo "Creating secret: $key"

  curl -s -o /dev/null -w "" --request DELETE \
    --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
    "${GITLAB_INSTALLATION_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/variables/$key" \
    >/dev/null 2>&1 || true

  SECRET_RESPONSE=$(curl -s --request POST \
    --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
    --header "Content-Type: application/json" \
    --data "$(jq -n \
      --arg key "$key" \
      --arg value "$value" \
      '{ key: $key, value: $value, protected: false, masked: true }')" \
    "${GITLAB_INSTALLATION_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/variables"
  )

  if echo "$SECRET_RESPONSE" | jq -e '.key' > /dev/null 2>&1; then
    echo "Secret $key created successfully"
  else
    echo "Error creating $key secret:"
    echo "$SECRET_RESPONSE" | jq
  fi
done