#!/bin/bash

echo '{
	"results": [
		{
			"name": "http.rpm",
			"title": "Throughput",
			"unit": "rpm",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		},
		{
			"name": "http.response_time",
			"title": "Response time",
			"unit": "ms",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		},
		{
			"name": "http.error_rate",
			"title": "Error rate",
			"unit": "%",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		},
		{
			"name": "system.cpu_usage_percentage",
			"title": "Cpu usage",
			"unit": "%",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		},
		{
			"name": "system.memory_usage_percentage",
			"title": "Memory usage",
			"unit": "%",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["scope_id", "instance_id"]
		},
		{
			"name": "http.healthcheck_count",
			"title": "Healthcheck",
			"unit": "check",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		},
		{
			"name": "http.healthcheck_fail",
			"title": "Healthcheck failures",
			"unit": "count",
			"available_filters": ["scope_id", "instance_id"],
			"available_group_by": ["instance_id"]
		}
	]
}'