#!/bin/bash

REPLICAS=$(echo "$CONTEXT" | jq -r .blue_replicas)

np_naming_apply_to_context || exit 1

source "$OVERRIDES_PATH/deployment/build_deployment" --replicas="$REPLICAS"

export DEPLOYMENT_ID=$NEW_DEPLOYMENT_ID

CONTEXT="$ORIGINAL_CONTEXT"