#!/bin/bash

DEPLOYMENT_PATH="$OUTPUT_DIR/deployment-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
SECRET_PATH="$OUTPUT_DIR/secret-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
CONTEXT_PATH="$OUTPUT_DIR/context-$SCOPE_ID.json"

echo "$CONTEXT" | jq --arg replicas "$REPLICAS" '. + {replicas: $replicas}' > "$CONTEXT_PATH"

echo "Building Template: $DEPLOYMENT_TEMPLATE to $DEPLOYMENT_PATH"

gomplate -c .="$CONTEXT_PATH" \
  --file "$DEPLOYMENT_TEMPLATE" \
  --out "$DEPLOYMENT_PATH"

TEMPLATE_GENERATION_STATUS=$?

if [[ $TEMPLATE_GENERATION_STATUS -ne 0 ]]; then
    echo "Error building deployment template"
    exit 1
fi

echo "Building Template: $SECRET_TEMPLATE to $SECRET_PATH"

gomplate -c .="$CONTEXT_PATH" \
  --file "$SECRET_TEMPLATE" \
  --out "$SECRET_PATH"

TEMPLATE_GENERATION_STATUS=$?

if [[ $TEMPLATE_GENERATION_STATUS -ne 0 ]]; then
    echo "Error building secret template"
    exit 1
fi

rm "$CONTEXT_PATH"
