#!/bin/bash

NRN=$(echo "$NP_ACTION_CONTEXT" | jq -r .notification.nrn)

ACCOUNT_ID=$(echo "$NRN" | sed -n 's/.*account=\([0-9]*\).*/\1/p')
NAMESPACE_ID=$(echo "$NRN" | sed -n 's/.*namespace=\([0-9]*\).*/\1/p')
APPLICATION_ID=$(echo "$NRN" | sed -n 's/.*application=\([0-9]*\).*/\1/p')

NAMESPACE=$(np namespace read --format json --id "$NAMESPACE_ID")

APPLICATION=$(np application read --format json --id "$APPLICATION_ID")

APPLICATION_SLUG=$(echo "$APPLICATION" | jq -r .slug)
NAMESPACE_SLUG=$(echo "$NAMESPACE" | jq -r .slug)

export ACCOUNT_ID

export NAMESPACE
export NAMESPACE_ID
export NAMESPACE_SLUG

export APPLICATION
export APPLICATION_ID
export APPLICATION_SLUG
export NRN
