#!/bin/bash

ASSET_REPOSITORY=$(np provider list --categories assets-repository --nrn "$NRN" --format json | jq ".results[0]")
ASSET_REPOSITORY_SPEC=$(echo "$ASSET_REPOSITORY" | jq -r .specification_id)

REPOSITORY_PROVIDER=$(np provider specification read --id "$ASSET_REPOSITORY_SPEC" --format json | jq -r .slug)

ASSET_REPOSITORY_SCRIPT_PATH="application/scripts/asset-repo/$REPOSITORY_PROVIDER"

export ASSET_REPOSITORY_TYPE
export ASSET_REPOSITORY

export ASSET_REPOSITORY_SCRIPT_PATH

np service workflow exec --workflow application/workflows/create_asset_repository.yaml