include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: build context
    type: script
    file: "$SERVICE_PATH/scope/build_context"
    output:
      - name: CONTEXT
        type: environment
      - name: SCOPE_VISIBILITY
        type: environment
      - name: SCOPE_DOMAIN
        type: environment
      - name: OUTPUT_DIR
        type: environment
  - name: networking
    type: workflow
    steps:
      - name: generate domain
        type: script
        file: "$SERVICE_PATH/scope/networking/dns/domain/generate_domain"
        output:
          - name: SCOPE_DOMAIN
            type: environment
      - name: create dns
        type: script
        file: "$SERVICE_PATH/scope/networking/dns/manage_dns"
        configuration:
          ACTION: CREATE
        pre:
          name: build dns context
          type: script
          file: "$SERVICE_PATH/scope/networking/dns/build_dns_context"
          output:
            - name: HOSTED_PUBLIC_ZONE_ID
              type: environment
            - name: HOSTED_PRIVATE_ZONE_ID
              type: environment
