include:
  - "$SERVICE_PATH/values.yaml"
steps:
  - name: build context
    type: script
    file: "$SERVICE_PATH/scope/build_context"
    output:
      - name: CONTEXT
        type: environment
      - name: OUTPUT_DIR
        type: environment
  - name: run status checks
    type: script
    file: "$SERVICE_PATH/scope/status_checks/run_checks"