#!/bin/bash

echo '{
	"results": [
		{
			"name": "http.rpm",
			"title": "Throughput",
			"unit": "rpm",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["pod"]
		},
		{
			"name": "http.response_time",
			"title": "Response time",
			"unit": "ms",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["pod"]
		},
		{
			"name": "http.error_rate",
			"title": "Error rate",
			"unit": "%",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["pod"]
		},
		{
			"name": "system.cpu_usage_percentage",
			"title": "Cpu usage",
			"unit": "%",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["pod"]
		},
		{
			"name": "system.memory_usage_percentage",
			"title": "Memory usage percentage",
			"unit": "%",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["scope_id", "pod"]
		},
		{
			"name": "system.used_memory_kb",
			"title": "Memory usage in kb",
			"unit": "kb",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["scope_id", "pod"]
		},
		{
			"name": "http.healthcheck_count",
			"title": "Healthy Pods",
			"unit": "check",
			"available_filters": ["scope_id", "pod"],
			"available_group_by": ["pod"]
		}
	]
}'