#!/bin/bash

K8S_NAMESPACE="nullplatform"
LABEL_SELECTOR="nullplatform=true"
if [[ -n "$APPLICATION_ID" && "$APPLICATION_ID" != "null" ]]; then
 LABEL_SELECTOR="$LABEL_SELECTOR,application_id=$APPLICATION_ID"
fi
if [[ -n "$SCOPE_ID" && "$SCOPE_ID" != "null" ]]; then
 LABEL_SELECTOR="$LABEL_SELECTOR,scope_id=$SCOPE_ID"
fi
if [[ -n "$DEPLOYMENT_ID" && "$DEPLOYMENT_ID" != "null" ]]; then
 LABEL_SELECTOR="$LABEL_SELECTOR,deployment_id=$DEPLOYMENT_ID"
fi

PODS=$(kubectl get pods -n "$K8S_NAMESPACE" -l "$LABEL_SELECTOR" -o json)

echo "$PODS" | jq --argjson limit ${LIMIT:-10} '{
 results: .items[:$limit] | map({
   id: .metadata.name,
   selector: .metadata.labels,
   details: .spec.containers[0] | {name, image, ports},
   state: .status.phase,
   launch_time: .metadata.creationTimestamp,
   spot: (.spec.nodeName // "" | test("spot"; "i"))
 })
}'