#!/bin/bash

export EXTERNAL_ID=$(echo "$NP_ACTION_CONTEXT" | jq -r '.notification.external_id // empty')
export PARAMETER_ID=$(echo "$NP_ACTION_CONTEXT" | jq -r '.notification.parameter_id // empty')
