#!/bin/bash
cd $WORKING_DIRECTORY
WORKFLOW_PATH="$SERVICE_PATH/metric/workflows/metric.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/metric/workflows/metric.yaml"

if [[ "$NOTIFICATION_ACTION" == "metric:list" ]]; then
  WORKFLOW_PATH="$SERVICE_PATH/metric/workflows/list.yaml"
  OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/metric/workflows/list.yaml"
fi

CMD="np service workflow exec --no-output --workflow $WORKFLOW_PATH"

if [[ -f "$OVERRIDES_WORKFLOW_PATH" ]]; then
  CMD="$CMD --overrides $OVERRIDES_WORKFLOW_PATH"
fi

eval $CMD
