#!/bin/bash

WORKFLOW_PATH="$SERVICE_PATH/metric/workflows/metric.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/metric/workflows/metric.yaml"

if [[ "$NOTIFICATION_ACTION" == "metric:list" ]]; then
  WORKFLOW_PATH="$SERVICE_PATH/metric/workflows/list.yaml"
  OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/metric/workflows/list.yaml"
fi

CMD="np service workflow exec --no-output --workflow $WORKFLOW_PATH"

IFS=',' read -ra OVERRIDE_PATHS <<< "$OVERRIDES_PATH"
for path in "${OVERRIDE_PATHS[@]}"; do
  # Trim whitespace
  path=$(echo "$path" | xargs)
  OVERRIDE_WORKFLOW_PATH="$path/metric/workflows/$ACTION_TO_EXECUTE.yaml"
  if [[ -f "$OVERRIDE_WORKFLOW_PATH" ]]; then
    CMD="$CMD --overrides $OVERRIDE_WORKFLOW_PATH"
  fi
done

eval $CMD