#!/bin/bash

echo "This is a test commit"

echo "This is a test commit2"


echo "This is a test commit3"


echo "this is a test commit 4"

echo "this is a test commit 5"


echo "Test commit 6"


echo "Test commit 7"

K8S_NAMESPACE=$(echo "$CONTEXT" | jq -r --arg default "$K8S_NAMESPACE" '
  .providers["container-orchestration"].cluster.namespace // $default
')

DOMAIN=$(echo "$CONTEXT" | jq -r --arg default "$DOMAIN" '
  .providers["cloud-providers"].networking.domain_name // $default
')

USE_ACCOUNT_SLUG=$(echo "$CONTEXT" | jq -r --arg default "$USE_ACCOUNT_SLUG" '
  .providers["cloud-providers"].networking.application_domain // $default
')

REGION=$(echo "$CONTEXT" | jq -r '.providers["cloud-providers"].account.region // "us-east-1"')

SCOPE_VISIBILITY=$(echo "$CONTEXT" | jq -r '.scope.capabilities.visibility')
SCOPE_DOMAIN=$(echo "$CONTEXT" | jq .scope.domain -r)

eval "$(echo "$CONTEXT" | jq -r '.scope.nrn | "
export ORGANIZATION_ID=\(capture("organization=(?<id>\\d+)").id)
export ACCOUNT_ID=\(capture("account=(?<id>\\d+)").id)
export NAMESPACE_ID=\(capture("namespace=(?<id>\\d+)").id)
export APPLICATION_ID=\(capture("application=(?<id>\\d+)").id)
"')"

SCOPE_ID=$(echo "$CONTEXT" | jq -r '.scope.id')

export SCOPE_VISIBILITY
export SCOPE_DOMAIN

if [ "$SCOPE_VISIBILITY" = "public" ]; then
    export INGRESS_VISIBILITY="internet-facing"
    export GATEWAY_NAME="${PUBLIC_GATEWAY_NAME:-gateway-public}"
else
    export INGRESS_VISIBILITY="internal"
    export GATEWAY_NAME="${PRIVATE_GATEWAY_NAME:-gateway-internal}"
fi

K8S_MODIFIERS="${K8S_MODIFIERS:-"{}"}"
K8S_MODIFIERS=$(echo "$K8S_MODIFIERS" | jq .)

ALB_NAME="k8s-nullplatform-$INGRESS_VISIBILITY"

if [ "$INGRESS_VISIBILITY" = "internet-facing" ]; then
    ALB_NAME=$(echo "$CONTEXT" | jq -r --arg default "$ALB_NAME" '.providers["container-orchestration"].balancer.public_name // $default')
else
    ALB_NAME=$(echo "$CONTEXT" | jq -r --arg default "$ALB_NAME" '.providers["container-orchestration"].balancer.private_name // $default')
fi

CONTEXT=$(echo "$CONTEXT" | jq \
          --arg ingress_visibility "$INGRESS_VISIBILITY" \
          --arg k8s_namespace "$K8S_NAMESPACE" \
          --arg region "$REGION" \
          --arg gateway_name "$GATEWAY_NAME" \
          --arg alb_name "$ALB_NAME" \
          --argjson modifiers "$K8S_MODIFIERS" \
          '. + {ingress_visibility: $ingress_visibility, k8s_namespace: $k8s_namespace, gateway_name: $gateway_name, region: $region, k8s_modifiers: $modifiers, alb_name: $alb_name}')

export OUTPUT_DIR="$SERVICE_PATH/output/$SCOPE_ID"
export CONTEXT
export REGION

mkdir -p "$OUTPUT_DIR"




