#!/bin/bash

DEPLOYMENT_ID=$(echo "$CONTEXT" | jq .scope.current_active_deployment -r)
SCOPE_ID=$(echo "$CONTEXT" | jq .scope.id -r)

K8S_NAMESPACE=$(echo "$CONTEXT" | jq -r --arg default "$K8S_NAMESPACE" '
  .providers["container-orchestration"].cluster.namespace // $default
')

DEPLOYMENT=$(kubectl get deployment -n "$K8S_NAMESPACE" -l "name=d-$SCOPE_ID-$DEPLOYMENT_ID" -o jsonpath="{.items[0].metadata.name}" 2>/dev/null )

kubectl rollout restart -n "$K8S_NAMESPACE" "deployment/$DEPLOYMENT"

kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$DEPLOYMENT" -w
