#!/bin/bash

REPLICAS=$(echo "$CONTEXT" | jq -r .blue_replicas)

export NEW_DEPLOYMENT_ID=$DEPLOYMENT_ID

export DEPLOYMENT_ID=$(echo "$CONTEXT" | jq .scope.current_active_deployment -r)

CONTEXT=$(echo "$CONTEXT" | jq \
  --arg deployment_id "$DEPLOYMENT_ID" \
  '.deployment.id = $deployment_id')

source "$SERVICE_PATH/deployment/build_deployment" --replicas="$REPLICAS"

export DEPLOYMENT_ID=$NEW_DEPLOYMENT_ID

CONTEXT=$(echo "$CONTEXT" | jq \
  --arg deployment_id "$DEPLOYMENT_ID" \
  '.deployment.id = $deployment_id')