#!/bin/bash

TEMPLATE=""

for arg in "$@"; do
  case $arg in
    --template=*) TEMPLATE="${arg#*=}" ;;
  esac
done

echo "Creating $INGRESS_VISIBILITY ingress..."

INGRESS_FILE="$OUTPUT_DIR/ingress-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
CONTEXT_PATH="$OUTPUT_DIR/context-$SCOPE_ID.json"

echo "$CONTEXT" > "$CONTEXT_PATH"

gomplate -c .="$CONTEXT_PATH" \
  --file "$TEMPLATE" \
  --out "$INGRESS_FILE"

rm "$CONTEXT_PATH"