#!/bin/bash

if ! command -v jq &> /dev/null; then
    exit 1
fi

if [ "$1" ]; then
    NP_ACTION_CONTEXT="$1"
elif [ -n "$NP_ACTION_CONTEXT" ]; then
    # Use the environment variable
    :
else
    # Read from stdin
    read -r NP_ACTION_CONTEXT
fi

WORKFLOW_PATH="$SERVICE_PATH/instance/workflows/list.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_WORKFLOW_PATH/instance/workflows/list.yaml"

CMD="np service workflow exec --no-output --build-context --workflow $WORKFLOW_PATH"

if [[ -f "$OVERRIDES_WORKFLOW_PATH" ]]; then
  CMD="$CMD --overrides $OVERRIDES_WORKFLOW_PATH"
fi

eval "$CMD"